<?php

use Illuminate\Database\Seeder;
use App\Model\Region;
class ComunasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table('comunas')->insert([

			['region_id' => Region::find(1)->id, 'nombre'    =>'IQUIQUE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(1)->id, 'nombre'    =>'ALTO HOSPICIO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(1)->id, 'nombre'    =>'POZO ALMONTE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(1)->id, 'nombre'    =>'CAMIÑA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(1)->id, 'nombre'    =>'COLCHANE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(1)->id, 'nombre'    =>'HUARA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(1)->id, 'nombre'    =>'PICA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(2)->id, 'nombre'    =>'ANTOFAGASTA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(2)->id, 'nombre'    =>'MEJILLONES', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(2)->id, 'nombre'    =>'SIERRA GORDA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(2)->id, 'nombre'    =>'TALTAL', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(2)->id, 'nombre'    =>'CALAMA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(2)->id, 'nombre'    =>'OLLAGUE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(2)->id, 'nombre'    =>'SAN PEDRO DE ATACAMA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(2)->id, 'nombre'    =>'TOCOPILLA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(2)->id, 'nombre'    =>'MARIA ELENA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(3)->id, 'nombre'    =>'CHAÑARAL', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(3)->id, 'nombre'    =>'DIEGO DE ALMAGRO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(3)->id, 'nombre'    =>'COPIAPO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(3)->id, 'nombre'    =>'CALDERA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(3)->id, 'nombre'    =>'TIERRA AMARILLA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(3)->id, 'nombre'    =>'VALLENAR', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(3)->id, 'nombre'    =>'ALTO DEL CARMEN', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(3)->id, 'nombre'    =>'FREIRINA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(3)->id, 'nombre'    =>'HUASCO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(4)->id, 'nombre'    =>'LOS VILOS', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(4)->id, 'nombre'    =>'SALAMANCA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(4)->id, 'nombre'    =>'ILLAPEL', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(4)->id, 'nombre'    =>'HUENTELAUQUEN', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(4)->id, 'nombre'    =>'PICHIDANGUI', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(4)->id, 'nombre'    =>'QUILIMARI', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(4)->id, 'nombre'    =>'LOS MOLLES', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(4)->id, 'nombre'    =>'CATAPILCO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(4)->id, 'nombre'    =>'CAIMANES ', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(4)->id, 'nombre'    =>'GUANGUALI', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(4)->id, 'nombre'    =>'LA BALLENA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(4)->id, 'nombre'    =>'PICHICUI', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(4)->id, 'nombre'    =>'CANELA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(4)->id, 'nombre'    =>'LA SERENA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(4)->id, 'nombre'    =>'COQUIMBO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(4)->id, 'nombre'    =>'ANDACOLLO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(4)->id, 'nombre'    =>'LA HIGUERA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(4)->id, 'nombre'    =>'PAIGUANO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(4)->id, 'nombre'    =>'VICUÑA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(4)->id, 'nombre'    =>'OVALLE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(4)->id, 'nombre'    =>'COMBARBALA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(4)->id, 'nombre'    =>'MONTE PATRIA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(4)->id, 'nombre'    =>'PUNITAQUI', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(4)->id, 'nombre'    =>'RIO HURTADO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'ISLA DE PASCUA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'LOS ANDES', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'CALLE LARGA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'RINCONADA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'SAN ESTEBAN', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'LA LIGUA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'CABILDO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'PAPUDO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'PETORCA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'ZAPALLAR', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'CACHAGUA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'MAITENCILLO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'MARBELLA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'QUILLOTA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'CALERA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'HIJUELAS', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'LA CRUZ', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'LIMACHE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'NOGALES', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'OLMUE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'SAN ANTONIO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'ALGARROBO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'CARTAGENA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'LAS BRISAS-STA MARIA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'SAN SEBASTIÀN', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'LAS CRUCES', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'ISLA NEGRA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'LLO-LLEO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'MIRASOL', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'TUNQUÈN', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'EL QUISCO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'EL TABO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'SANTO DOMINGO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'SAN FELIPE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'CATEMU', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'LLAILLAY', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'PANQUEHUE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'PUTAENDO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'SANTA MARIA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'VALPARAISO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'CASABLANCA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'CONCON', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'JUAN FERNANDEZ', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'PUCHUNCAVI', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'QUILPUE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'QUINTERO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'VILLA ALEMANA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'VIÑA DEL MAR', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'REÑACA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'BELLOTO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'CURAUMA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'LLIU LLIU', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'MANTAGUA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'LAGUNA VERDE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'VENTANAS', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(5)->id, 'nombre'    =>'HORCON', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'SAN VICENTE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'RANCAGUA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'CODEGUA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'COINCO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'COLTAUCO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'DOÑIHUE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'GRANEROS', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'LAS CABRAS', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'MACHALI', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'MALLOA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'MOSTAZAL', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'OLIVAR', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'PEUMO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'PICHIDEGUA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'QUINTA DE TILCOCO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'RENGO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'REQUINOA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'PICHILEMU', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'LA ESTRELLA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'LITUECHE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'MARCHIHUE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'NAVIDAD', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'PAREDONES', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'SAN FERNANDO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'PELEQUEN', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'ROSARIO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'QTA.DE TILCOCO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'ROMA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'TALCAREHUE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'PTE.NEGRO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'TINGUIRIRICA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'CHEPICA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'CHIMBARONGO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'LOLOL', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'NANCAGUA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'PALMILLA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'PERALILLO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'PLACILLA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'PUMANQUE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(6)->id, 'nombre'    =>'SANTA CRUZ', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'CAUQUENES', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'CHANCO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'PELLUHUE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'CURICO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'HUALAÑE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'LICANTEN', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'MOLINA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'RAUCO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'ROMERAL', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'SAGRADA FAMILIA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'TENO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'VICHUQUEN', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'TENO LA MONTAÑA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'MORZA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'HUEMUL DE MORZA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'LOS GUAICOS ', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'LOS NICHES', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'POTRERO GRANDE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'LONTUE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'PARQUE INGLES', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'CUMPEO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'SANGRADA FAMILIA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'VILLA PRAT', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'PUENTE PAULA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'LA HUERTA ', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'ILOCA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'EL DUAO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'LINARES', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'COLBUN', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'LONGAVI', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'PARRAL', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'RETIRO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'SAN JAVIER', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'VILLA ALEGRE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'YERBAS BUENAS', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'TALCA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'CONSTITUCION', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'CUREPTO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'EMPEDRADO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'MAULE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'PELARCO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'PENCAHUE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'RIO CLARO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'SAN CLEMENTE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(7)->id, 'nombre'    =>'SAN RAFAEL', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'LEBU', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'ARAUCO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'CONTULMO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'CURANILAHUE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'LOS ALAMOS', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'TIRUA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'CAÑETE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'LOS ANGELES', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'ANTUCO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'CABRERO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'LAJA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'MULCHEN', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'NACIMIENTO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'NEGRETE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'QUILACO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'QUILLECO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'SAN ROSENDO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'SANTA BARBARA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'TUCAPEL', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'YUMBEL', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'ALTO BIOBIO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'TALCAHUANO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'TOME', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'HUALPEN', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'CONCEPCION', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'CORONEL', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'CHIGUAYANTE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'FLORIDA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'HUALQUI', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'LOTA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'PENCO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'SAN PEDRO DE LA PAZ', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'SANTA JUANA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'CHILLAN', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'BULNES', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'COBQUECURA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'COELEMU', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'COIHUECO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'CHILLAN VIEJO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'EL CARMEN', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'NINHUE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'ÑIQUEN', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'PEMUCO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'PINTO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'PORTEZUELO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'QUILLON', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'QUIRIHUE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'RANQUIL', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'SAN CARLOS', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'SAN FABIAN', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'SAN IGNACIO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'SAN NICOLAS', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'BULI', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'CACHAPOAL', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'CATO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'CAMPANARIO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'CHOLHUAN', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'CONFLUENCIA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'EL SAUCE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'HUAPE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'HUEPIL', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'LAS TERMAS', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'LAS TRANCAS ', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'NAHUELTORO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'NEBUCO ', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'NINQUIHUE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'ÑIPAS(CAMINO QUINCHAM.)', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'ÑIPAS(POR AUTOP. ITATA)', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'PUEBLO SECO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'QUINCHAMALI', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'QUIRIQUINA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'RECINTO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'RUCAPEQUEN', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'SANTA CLARA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'TREGUACO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(8)->id, 'nombre'    =>'YUNGAY', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'PUCON', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'SAAVEDRA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'TEODORO SCHMIDT', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'TOLTEN', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'VILCUN', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'VILLARRICA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'CHOLCHOL', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'TEMUCO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'CARAHUE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'CUNCO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'CURARREHUE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'FREIRE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'GALVARINO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'GORBEA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'LAUTARO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'LONCOCHE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'MELIPEUCO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'NUEVA IMPERIAL', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'PADRE LAS CASAS', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'PERQUENCO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'PITRUFQUEN', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'ANGOL', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'COLLIPULLI', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'CURACAUTIN', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'ALHUE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'ERCILLA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'BUIN', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'LONQUIMAY', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'CALERA DE TANGO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'LOS SAUCES', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'CERRILLOS', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'LUMACO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'CERRO NAVIA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'PUREN', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'COLINA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'RENAICO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'CONCHALI', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'TRAIGUEN', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'CURACAVI', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(9)->id, 'nombre'    =>'VICTORIA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'EL BOSQUE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(10)->id,'nombre'    => 'CASTRO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'EL MONTE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(10)->id,'nombre'    => 'DALCAHUE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'ESTACION CENTRAL', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(10)->id,'nombre'    => 'PUQUELDON', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'HUECHURABA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(10)->id,'nombre'    => 'QUEILEN', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'INDEPENDENCIA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(10)->id,'nombre'    => 'QUELLON', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'ISLA DE MAIPO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(10)->id,'nombre'    => 'QUEMCHI', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'LA CISTERNA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(10)->id,'nombre'    => 'QUINCHAO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'LA FLORIDA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(10)->id,'nombre'    => 'ANCUD', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'LA GRANJA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(10)->id,'nombre'    => 'CHONCHI', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'LA PINTANA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(10)->id,'nombre'    => 'CURACO DE VELEZ', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'LA REINA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(10)->id,'nombre'    => 'PUERTO MONTT', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'LAMPA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(10)->id,'nombre'    => 'CALBUCO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'LAS CONDES', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(10)->id,'nombre'    => 'COCHAMO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'LO BARNECHEA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(10)->id,'nombre'    => 'FRESIA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'LO ESPEJO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(10)->id,'nombre'    => 'FRUTILLAR', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'LO PRADO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(10)->id,'nombre'    => 'LOS MUERMOS', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'MACUL', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(10)->id,'nombre'    => 'LLANQUIHUE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'MAIPU', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(10)->id,'nombre'    => 'MAULLIN', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'MARIA PINTO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(10)->id,'nombre'    => 'PUERTO VARAS', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'MELIPILLA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(10)->id,'nombre'    => 'RIO NEGRO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'PAINE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(10)->id,'nombre'    => 'SAN JUAN DE LA COSTA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'PEDRO AGUIRRE CERDA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(10)->id,'nombre'    => 'SAN PABLO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'PEÑAFLOR', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(10)->id,'nombre'    => 'OSORNO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'PEÑALOLEN', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(10)->id,'nombre'    => 'PUERTO OCTAY', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'PIRQUE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(10)->id,'nombre'    => 'PURRANQUE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'PROVIDENCIA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(10)->id,'nombre'    => 'PUYEHUE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'PUDAHUEL', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(10)->id,'nombre'    => 'CHAITEN', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'PUENTE ALTO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(10)->id,'nombre'    => 'FUTALEUFU', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'QUILICURA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(10)->id,'nombre'    => 'HUALAIHUE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'QUINTA NORMAL', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(10)->id,'nombre'    => 'PALENA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'RECOLETA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(11)->id,'nombre'    => 'AISEN', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'RENCA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(11)->id,'nombre'    => 'CISNES', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'SAN BERNARDO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(11)->id,'nombre'    => 'GUAITECAS', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'SAN JOAQUIN', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(11)->id,'nombre'    => 'COCHRANE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'SAN JOSE DE MAIPO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(11)->id,'nombre'    => 'O HIGGINS', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'SAN MIGUEL', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(11)->id,'nombre'    => 'TORTEL', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'SAN PEDRO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(11)->id,'nombre'    => 'COIHAIQUE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'SAN RAMON', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(11)->id,'nombre'    => 'LAGO VERDE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'SANTIAGO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(11)->id,'nombre'    => 'CHILE CHICO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'TALAGANTE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(11)->id,'nombre'    => 'RIO IBAÑEZ', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'TILTIL', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(12)->id,'nombre'    => 'CABO DE HORNOS (EX-NAVARINO)', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'VITACURA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(12)->id,'nombre'    => 'ANTARTICA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'ÑUÑOA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(12)->id,'nombre'    => 'PUNTA ARENAS', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(12)->id,'nombre'    => 'LAGUNA BLANCA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(12)->id,'nombre'    => 'RIO VERDE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(12)->id,'nombre'    => 'SAN GREGORIO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(12)->id,'nombre'    => 'PORVENIR', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(12)->id,'nombre'    => 'PRIMAVERA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(12)->id,'nombre'    => 'TIMAUKEL', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'PADRE HURTADO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(12)->id,'nombre'    => 'NATALES', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(12)->id,'nombre'    => 'TORRES DEL PAINE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(14)->id,'nombre'    => 'VALDIVIA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(14)->id,'nombre'    => 'CORRAL', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(14)->id,'nombre'    => 'LANCO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(14)->id,'nombre'    => 'LOS LAGOS', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(14)->id,'nombre'    => 'MAFIL', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(14)->id,'nombre'    => 'MARIQUINA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(14)->id,'nombre'    => 'PAILLACO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(14)->id,'nombre'    => 'PANGUIPULLI', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(14)->id,'nombre'    => 'LA UNION', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(14)->id,'nombre'    => 'FUTRONO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(14)->id,'nombre'    => 'LAGO RANCO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(14)->id,'nombre'    => 'RIO BUENO', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(15)->id,'nombre'    => 'ARICA', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(15)->id,'nombre'    => 'CAMARONES', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(15)->id,'nombre'    => 'PUTRE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(15)->id,'nombre'    => 'GENERAL LAGOS', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")],
			['region_id' =>Region::find(13)->id,'nombre'    => 'INEXISTENTE', 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")]

		]);	

    }
}
