<?php

use Illuminate\Database\Seeder;

class NominaTiendaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

       DB::table('nomina_tienda')->insert([

		['id'=>'1', 'cod2' => '2', 'tienda'=>'EASY ANTOFAGASTA', 'activado' =>'1'],
		['id'=>'2', 'cod2' => '2', 'tienda'=>'EASY CALAMA', 'activado' =>'1'],
		['id'=>'3', 'cod2' => '2', 'tienda'=>'EASY COPIAPO', 'activado' =>'1'],
		['id'=>'4', 'cod2' => '2', 'tienda'=>'EASY LA SERENA','activado' => '1'],
		['id'=>'5', 'cod2' => '2', 'tienda'=>'EASY VALPARAISO', 'activado' =>'1'],
		['id'=>'6', 'cod2' => '2', 'tienda'=>'EASY EL BELLOTO II', 'activado' =>'1'],
		['id'=>'7', 'cod2' => '2', 'tienda'=>'EASY VIÑA DEL MAR', 'activado' =>'1'],
		['id'=>'8', 'cod2' => '2', 'tienda'=>'EASY QUILLOTA', 'activado' =>'1'],
		['id'=>'9', 'cod2' => '2', 'tienda'=>' EASY RANCAGUA','activado' => '1'],
		['id'=>'10','cod2' =>  '2', 'tienda'=> 'EASY TALCA EL ARENAL', 'activado' =>'1'],
		['id'=>'11','cod2' =>  '2', 'tienda'=> 'EASY LINARES', 'activado' =>'1'],
		['id'=>'12','cod2' =>  '2', 'tienda'=> 'EASY CURICO O HIGGINS', 'activado' =>'1'],
		['id'=>'13','cod2' =>  '2', 'tienda'=> 'EASY CONCEPCION CASTELLON', 'activado' =>'1'],
		['id'=>'14','cod2' =>  '2', 'tienda'=> 'EASY CONCEPCION ALLESSANDRI','activado' => '1'],
		['id'=>'15','cod2' =>  '2', 'tienda'=> 'EASY CHILLAN', 'activado' =>'1'],
		['id'=>'16','cod2' =>  '2', 'tienda'=> 'EASY LOS ANGELES', 'activado' =>'1'],
		['id'=>'17','cod2' =>  '2', 'tienda'=> 'EASY TEMUCO', 'activado' =>'1'],
		['id'=>'18','cod2' =>  '2', 'tienda'=> 'EASY OSORNO DA VINCI', 'activado' =>'1'],
		['id'=>'19','cod2' =>  '2', 'tienda'=> 'EASY PUERTO MONTT', 'activado' =>'1'],
		['id'=>'20','cod2' =>  '2', 'tienda'=> 'EASY CERRILLOS', 'activado' =>'1'],
		['id'=>'21','cod2' =>  '2', 'tienda'=> 'EASY FLORIDA', 'activado' =>'1'],
		['id'=>'22','cod2' =>  '2', 'tienda'=> 'EASY LA DEHESA', 'activado' =>'1'],
		['id'=>'23','cod2' =>  '2', 'tienda'=> 'EASY KENNEDY', 'activado' =>'1'],
		['id'=>'24','cod2' =>  '2', 'tienda'=> 'EASY INTERNET', 'activado' =>'1'],
		['id'=>'25','cod2' =>  '2', 'tienda'=> 'EASY QUILIN', 'activado' =>'1'],
		['id'=>'26','cod2' =>  '2', 'tienda'=> 'EASY MAIPU', 'activado' =>'1'],
		['id'=>'27','cod2' =>  '2', 'tienda'=> 'EASY OCHAGAVIA', 'activado' =>'1'],
		['id'=>'28','cod2' =>  '2', 'tienda'=> 'EASY LA REINA PADRE HURTADO', 'activado' =>'1'],
		['id'=>'29','cod2' =>  '2', 'tienda'=> 'EASY QUILICURA', 'activado' =>'1'],
		['id'=>'30','cod2' =>  '2', 'tienda'=> 'EASY EL LLANO SUBERCASEAUX', 'activado' =>'1'],
		['id'=>'31','cod2' =>  '2', 'tienda'=> 'EASY PUENTE ALTO - BARNABITAS', 'activado' =>'1'],
		['id'=>'32','cod2' =>  '1', 'tienda'=> 'HC IQUIQUE', 'activado' =>'1'],
		['id'=>'33','cod2' =>  '1', 'tienda'=> 'CO ANTOFAGASTA', 'activado' =>'1'],
		['id'=>'34','cod2' =>  '1', 'tienda'=> 'HC ANTOFAGASTA', 'activado' =>'1'],
		['id'=>'35','cod2' =>  '1', 'tienda'=> 'HC CALAMA', 'activado' =>'1'],
		['id'=>'36','cod2' =>  '1', 'tienda'=> 'CO VALLENAR','activado' =>'1'],
		['id'=>'37','cod2' =>  '1', 'tienda'=> 'HC COPIAPÓ', 'activado' =>'1'],
		['id'=>'38','cod2' =>  '1', 'tienda'=> 'HC COQUIMBO', 'activado' =>'1'],
		['id'=>'39','cod2' =>  '1', 'tienda'=> 'HC LA SERENA','activado' => '1'],
		['id'=>'40','cod2' =>  '1', 'tienda'=> 'CO VALPARAÍSO', 'activado' =>'1'],
		['id'=>'41','cod2' =>  '1', 'tienda'=> 'HC VIÑA DEL MAR','activado' => '1'],
		['id'=>'42','cod2' =>  '1', 'tienda'=> 'CO REÑACA ALTO', 'activado' =>'1'],
		['id'=>'43','cod2' =>  '1', 'tienda'=> 'CO VIÑA DEL MAR','activado' => '1'],
		['id'=>'44','cod2' =>  '1', 'tienda'=> 'HC CALERA', 'activado' =>'1'],
		['id'=>'45','cod2' =>  '1', 'tienda'=> 'HC SAN FELIPE', 'activado' =>'1'],
		['id'=>'46','cod2' =>  '1', 'tienda'=> 'HC EL BELLOTO', 'activado' =>'1'],
		['id'=>'47','cod2' =>  '1', 'tienda'=> 'HC RANCAGUA', 'activado' =>'1'],
		['id'=>'48','cod2' =>  '1', 'tienda'=> 'CO RANCAGUA', 'activado' =>'1'],
		['id'=>'49','cod2' =>  '1', 'tienda'=> 'HC TALCA', 'activado' =>'1'],
		['id'=>'50','cod2' =>  '1', 'tienda'=> 'HC LINARES','activado' => '1'],
		['id'=>'51','cod2' =>  '1', 'tienda'=> 'HC CURICÓ', 'activado' =>'1'],
		['id'=>'52','cod2' =>  '1', 'tienda'=> 'HC MALL PLAZA CONCEPCIÓN', 'activado' =>'1'],
		['id'=>'53','cod2' =>  '1', 'tienda'=> 'HC CONCEPCIÓN', 'activado' =>'1'],
		['id'=>'54','cod2' =>  '1', 'tienda'=> 'HC CHILLÁN ', 'activado' =>'1'],
		['id'=>'55','cod2' =>  '1', 'tienda'=> 'HC LOS ANGELES', 'activado' =>'1'],
		['id'=>'56','cod2' =>  '1', 'tienda'=> 'HC EL TRÉBOL', 'activado' =>'1'],
		['id'=>'57','cod2' =>  '1', 'tienda'=> 'CO TALCAHUANO','activado' => '1'],
		['id'=>'58','cod2' =>  '1', 'tienda'=> 'HC ANGOL', 'activado' =>'1'],
		['id'=>'59','cod2' =>  '1', 'tienda'=> 'HC TEMUCO CAUTÍN', 'activado' =>'1'],
		['id'=>'60','cod2' =>  '1', 'tienda'=> 'HC VILLARRICA', '1'],
		['id'=>'61','cod2' =>  '1', 'tienda'=> 'HC OSORNO', '1'],
		['id'=>'62','cod2' =>  '1', 'tienda'=> 'CO CASTRO', '1'],
		['id'=>'63','cod2' =>  '1', 'tienda'=> 'HC PUERTO MONTT', '1'],
		['id'=>'64','cod2' =>  '1', 'tienda'=> 'HC COYHAIQUE', '1'],
		['id'=>'65','cod2' =>  '1', 'tienda'=> 'HC PUNTA ARENAS', '1'],
		['id'=>'66','cod2' =>  '1', 'tienda'=> 'HC VALDIVIA', '1'],
		['id'=>'67','cod2' =>  '1', 'tienda'=> 'HC ARICA', '1'],
		['id'=>'68','cod2' =>  '1', 'tienda'=> 'HC CERRILLOS', '1'],
		['id'=>'69','cod2' =>  '1', 'tienda'=> 'HC EL BOSQUE', '1'],
		['id'=>'70','cod2' =>  '1', 'tienda'=> 'HC ESTACIÓN CENTRAL', '1'],
		['id'=>'71','cod2' =>  '1', 'tienda'=> 'HC HUECHURABA', 'activado' =>'1'],
		['id'=>'72','cod2' =>  '1', 'tienda'=> 'CO HUECHURABA', 'activado' =>'1'],
		['id'=>'73','cod2' =>  '1', 'tienda'=> 'HC PLAZA VESPUCIO', 'activado' =>'1'],
		['id'=>'74','cod2' =>  '1', 'tienda'=> 'CO LA FLORIDA', 'activado' =>'1'],
		['id'=>'75','cod2' =>  '1', 'tienda'=> 'HC NUEVA LA FLORIDA', 'activado' =>'1'],
		['id'=>'76','cod2' =>  '1', 'tienda'=> 'HC LA REINA', 'activado' =>'1'],
		['id'=>'77','cod2' =>  '1', 'tienda'=> 'HC LAS CONDES', 'activado' =>'1'],
		['id'=>'78','cod2' =>  '1', 'tienda'=> 'CO CANTAGALLO', 'activado' =>'1'],
		['id'=>'79','cod2' =>  '1', 'tienda'=> 'HOMY','activado' => '1'],
		['id'=>'80','cod2' =>  '1', 'tienda'=> 'HC PARQUE ARAUCO', 'activado' =>'1'],
		['id'=>'81','cod2' =>  '1', 'tienda'=> 'CO MAIPÚ', 'activado' =>'1'],
		['id'=>'82','cod2' =>  '1', 'tienda'=> 'HC MAIPÚ', 'activado' =>'1'],
		['id'=>'83','cod2' =>  '1', 'tienda'=> 'HC ÑUÑOA', 'activado' =>'1'],
		['id'=>'84','cod2' =>  '1', 'tienda'=> 'HC ÑUBLE', 'activado' =>'1'],
		['id'=>'85','cod2' =>  '1', 'tienda'=> 'CO ÑUÑOA','activado' =>'1'],
		['id'=>'86','cod2' =>  '1', 'tienda'=> 'HC PUENTE ALTO', 'activado' =>'1'],
		['id'=>'87','cod2' =>  '1', 'tienda'=> 'HC SAN BERNARDO', 'activado' =>'1'],
		['id'=>'88','cod2' =>  '1', 'tienda'=> 'HC SAN MIGUEL', 'activado' =>'1'],
		['id'=>'89','cod2' =>  '3', 'tienda'=> 'HIGUERILLAS C. MATRIZ-M2', 'activado' =>'1'],
		['id'=>'90','cod2' =>  '3', 'tienda'=> 'HIGUERILLAS MAITENCILLO-M2','activado' => '1'],
		['id'=>'91','cod2' =>  '3', 'tienda'=> 'HIGUERILLAS QUINTERO','activado' => '1'],
		['id'=>'92','cod2' =>  '3', 'tienda'=> 'CAMARENA -M2', 'activado' =>'1'],
		['id'=>'93','cod2' =>  '3', 'tienda'=> 'SAN FRANCISCO', 'activado' =>'1'],
		['id'=>'94','cod2' =>  '3', 'tienda'=> 'OKEY S.A. ', 'activado' =>'1'],
		['id'=>'95','cod2' =>  '3', 'tienda'=> 'LONZA HERMANOS LTDA','activado' => '1'],
		['id'=>'96','cod2' =>  '3', 'tienda'=> 'DIMAFER M2 ','activado' => '1'],
		['id'=>'97','cod2' =>  '3', 'tienda'=> 'DIMAFER LTDA.', 'activado' =>'1'],
		['id'=>'98','cod2' =>  '3', 'tienda'=> 'PERSA', 'activado' =>'1'],
		['id'=>'99','cod2' =>  '3', 'tienda'=> 'FERRETERIA CARTAGENA - EL TABO LTDA.','activado' => '1'],
		['id'=>'100' , 'cod2' => '3', 'tienda'=> 'SADEMAT','activado' => '1'],
		['id'=>'101' , 'cod2' => '3', 'tienda'=> 'SOC. COM. MOLINA Y MARTINEZ','activado' => '1'],
		['id'=>'102' , 'cod2' => '3', 'tienda'=> 'COMERCIAL E INV. CROSUR LTDA.', 'activado' =>'1'],
		['id'=>'103' , 'cod2' => '3', 'tienda'=> 'FERGI (M2)', 'activado' =>'1'],
		['id'=>'104' , 'cod2' => '3', 'tienda'=> 'TORAL (M2)','activado' => '1'],
		['id'=>'105', 'cod2' => '3','tienda'=> 'DIEZCO ', 'activado' =>'1'],
		['id'=>'106', 'cod2' => '3','tienda'=> 'IN HOUSE','activado' => '1'],
		['id'=>'107', 'cod2' => '3','tienda'=> 'DIMAPLAC','activado' => '1'],
		['id'=>'108', 'cod2' => '3','tienda'=> 'AGRICOLA VILLARRICA', 'activado' =>'1'],
		['id'=>'109', 'cod2' => '3','tienda'=> 'COM. COLÓN ', 'activado' =>'1'],
		['id'=>'110', 'cod2' => '3','tienda'=> 'ESTABLECIMIENTOS MAIPO','activado' => '1'],
		['id'=>'111', 'cod2' => '3','tienda'=> 'EL CARPINTERO','activado' => '1'],
		['id'=>'112', 'cod2' => '3','tienda'=> 'ANDINA', 'activado' =>'1'],
		['id'=>'113', 'cod2' => '3','tienda'=> 'ANDINA CASA MATRIZ-M2', 'activado' =>'1'],
		['id'=>'114', 'cod2' => '3','tienda'=> 'ANDINA CONSTRUCTOR', 'activado' =>'1'],
		['id'=>'115', 'cod2' => '3','tienda'=> 'ANDINA MADERAS MAIPÚ', 'activado' =>'1'],
		['id'=>'116', 'cod2' => '3','tienda'=> 'ANDINA -M2', 'activado' =>'1'],
		['id'=>'117', 'cod2' => '3','tienda'=> 'FERRETERIA LONZA Y CÍA. LTDA.', 'activado' =>'1'],
		['id'=>'118', 'cod2' => '3','tienda'=> 'YOLITO', 'activado' =>'1'],
		['id'=>'119', 'cod2' => '3','tienda'=> 'J. RAVERA Y COMPAÑÍA LTDA.','activado' => '1'],
		['id'=>'120', 'cod2' => '3','tienda'=> 'FRINDT', 'activado' =>'1'],
		['id'=>'121', 'cod2' => '3','tienda'=> 'CONSTRUPLAZA CERÁMICAS','activado' => '1'],
		['id'=>'122', 'cod2' => '3','tienda'=> 'CONSTRUPLAZA ', 'activado' =>'1'],
		['id'=>'123', 'cod2' => '3','tienda'=> 'CONSTRUPLAZA -M2', 'activado' =>'1'],
		['id'=>'124', 'cod2' => '3','tienda'=> 'CONSTRUPLAZA PLACACENTRO ', 'activado' =>'1'],
		['id'=>'125', 'cod2' => '3','tienda'=> 'CONSTRUPLAZA FIERRO Y MAD', 'activado' =>'1'],
		['id'=>'126', 'cod2' => '3','tienda'=> 'LA OLLETA', 'activado' =>'1'],
		['id'=>'127', 'cod2' => '3','tienda'=> 'LA OLLETA PLACACENTRO ', 'activado' =>'1'],
		['id'=>'128', 'cod2' => '3','tienda'=> 'MLA CENTRO CONSTRUCTOR','activado' => '1'],
		['id'=>'129', 'cod2' => '3','tienda'=> 'DABED', 'activado' =>'1'],
		['id'=>'130', 'cod2' => '3','tienda'=> 'METROCUADRADO', 'activado' =>'1'],
		['id'=>'131', 'cod2' => '3','tienda'=> 'JORDAN ', 'activado' =>'1'],
		['id'=>'132', 'cod2' => '3','tienda'=> 'SUR','activado' => '1'],
		['id'=>'133', 'cod2' => '3','tienda'=> 'CAUPOLICÁN C. MATRIZ', 'activado' =>'1'],
		['id'=>'134', 'cod2' => '3','tienda'=> 'CAUPOLICÁN SUCURSAL', 'activado' =>'1'],
		['id'=>'135', 'cod2' => '3','tienda'=> 'PLACACENTRO AUSTRAL','activado' => '1'],
		['id'=>'136', 'cod2' => '3','tienda'=> 'AGUILA CONSTRUCTOR','activado' => '1'],
		['id'=>'137', 'cod2' => '3','tienda'=> 'EL AGUILA', 'activado' =>'1'],
		['id'=>'138', 'cod2' => '3','tienda'=> 'PLACACENTRO CALIFORNIA', 'activado' =>'1'],
		['id'=>'139', 'cod2' => '3','tienda'=> 'DISTR. AGRÍCOLA BUIN LTDA. ', 'activado' =>'1'],
		['id'=>'140', 'cod2' => '3','tienda'=> 'DAB-METROCUADRADO','activado' =>'1'],
		['id'=>'141', 'cod2' => '3','tienda'=> 'OVIMAQ', 'activado' =>'1'],
		['id'=>'142', 'cod2' => '3','tienda'=> 'OVIEDO', 'activado' =>'1'],
		['id'=>'143', 'cod2' => '3','tienda'=> 'PRAT M2', 'activado' =>'1'],
		['id'=>'144', 'cod2' => '3','tienda'=> 'PRAT CENTRO FERRETERO','activado' => '1'],
		['id'=>'145', 'cod2' => '3','tienda'=> 'PRAT CONSTRUCTOR', 'activado' =>'1'],
		['id'=>'146', 'cod2' => '3','tienda'=> 'BARRACA Y FERRETERÍA REAL','activado' => '1'],
		['id'=>'147', 'cod2' => '3','tienda'=> 'HOMECENTER REAL - M2', 'activado' =>'1'],
		['id'=>'148', 'cod2' => '3','tienda'=> 'GOMILA','activado' =>'1'],
		['id'=>'149', 'cod2' => '3','tienda'=> 'CORONA DE ARAGÓN ', 'activado' =>'1'],
		['id'=>'150', 'cod2' => '3','tienda'=> 'EUGENIO RAVERA Y CÍA. LTDA.', 'activado' =>'1'],
		['id'=>'151', 'cod2' => '3','tienda'=> 'MADRID CENTRO MADERAS', 'activado' =>'1'],
		['id'=>'152', 'cod2' => '3','tienda'=> 'MADRID IN HOUSE', 'activado' =>'1'],
		['id'=>'153', 'cod2' => '3','tienda'=> 'MADRID FERRETERIA', 'activado' =>'1'],
		['id'=>'154', 'cod2' => '3','tienda'=> 'WEITZLER', 'activado' =>'1'],
		['id'=>'155', 'cod2' => '3','tienda'=> 'PUNTO MAESTRO ','activado' => '1'],
		['id'=>'156', 'cod2' => '3','tienda'=> 'PIÑA HERMANOS S.A','activado' => '1'],
		['id'=>'157', 'cod2' => '3','tienda'=> 'NUEVA', 'activado' =>'1'],
		['id'=>'158', 'cod2' => '3','tienda'=> 'TIGERO ', 'activado' =>'1'],
		['id'=>'159', 'cod2' => '3','tienda'=> 'TIGERO CENTRO TERMINACIONES', 'activado' =>'1'],
		['id'=>'160', 'cod2' => '3','tienda'=> 'TIGERO CONSTRUCTOR IN HOUSE', 'activado' =>'1'],
		['id'=>'161', 'cod2' => '3','tienda'=> 'TIGERO FERRETERIA','activado' =>'1'],
		['id'=>'162', 'cod2' => '3','tienda'=> 'TIGERO BARRACA DE FIERROS', 'activado' =>'1'],
		['id'=>'163', 'cod2' => '3','tienda'=> 'TIGERO PLACA CENTRO','activado' =>'1'],
		['id'=>'164', 'cod2' => '3','tienda'=> 'LA NUEVA S.A.', 'activado' =>'1'],
		['id'=>'165', 'cod2' => '3','tienda'=> 'SAN  CRISTOBAL', 'activado' =>'1'],
		['id'=>'166', 'cod2' => '3','tienda'=> 'SAN JOAQUÍN ', 'activado' =>'1'],
		['id'=>'167', 'cod2' => '3','tienda'=> 'FERRETERIA 23 DE MARZO', 'activado' =>'1'],
		['id'=>'168', 'cod2' => '4','tienda'=> 'OTRO', 'activado' =>'1'],
		['id'=>'169', 'cod2' => '5','tienda'=> 'N/A', 'activado' =>'1'],
		['id'=>'170', 'cod2' => '6','tienda'=> 'CLIENTE', 'activado' =>'1'],
		['id'=>'171', 'cod2' => '7','tienda'=> 'N/A', 'activado' =>'1'],
		['id'=>'172', 'cod2' => '8','tienda'=> 'N/A', 'activado' =>'1'],
		['id'=>'173', 'cod2' => '9','tienda'=> 'N/A', 'activado' =>'1'],
		['id'=>'174', 'cod2' => '30','tienda'=> 'N/A', 'activado' =>'0'],
		['id'=>'175', 'cod2' => '6','tienda'=> 'N/A', 'activado' =>'1']

      ]);

    }
}